# fly.toml app configuration file generated for ocoup-server
app = "ocoup-server"
primary_region = "sjc" # Change to your preferred region

[build]
  # Reference the pre-built image from GitHub Container Registry
  # Replace USERNAME with your GitHub username
  image = "ghcr.io/USERNAME/ocoup-server:latest"

[env]
  # Add any environment variables the server needs here
  # EXAMPLE_VAR = "example_value"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

  [http_service.concurrency]
    type = "connections"
    hard_limit = 1000
    soft_limit = 500

[[http_service.ports]]
  handlers = ["http"]
  port = 80
  force_https = true

[[http_service.ports]]
  handlers = ["tls", "http"]
  port = 443

[checks]
  [checks.health]
    port = 8080
    type = "http"
    interval = "10s"
    timeout = "2s"
    grace_period = "5s"
    method = "get"
    path = "/"
    protocol = "http"